---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: my-go
          image: quay.io/lucarval/devfile-sample-go-basic:207b9d91c9521adb5ccd6529df7473352fd88d29@sha256:26c5ff115e4e79e13244d65dcce396c7b6bb5ed084900b44008f829c5bbf3016
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
