---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: my-go
          image: quay.io/lucarval/devfile-sample-go-basic:66f6c9e3ada23eb3e2150107db04c0d8e0c7c9bf@sha256:9d59f686ac92a2ff2d9660c249ed4aa90d957ca1a55e2ae13ff5e72269574590
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
