---
# This is an example ArgoCD application that deploys the resources from the deployment dir.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devfile-sample-go-basic
  namespace: openshift-gitops
spec:
  destination:
    namespace: devfile-sample-go-basic
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployment
    repoURL: https://github.com/lcarva/devfile-sample-go-basic-deploy.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 15s
      limit: 50
    syncOptions:
    - CreateNamespace=true
